# FSR stands for Force Sensitive Resistors.
# These sensors measure a resistance change according to the pressure applied.
# Units used are in Newtons (equivalently kg/m/s^2)
# http://doc.aldebaran.com/2-1/family/robots/fsr_robot.html

float32 l_foot_front_left
float32 l_foot_front_right
float32 l_foot_back_left
float32 l_foot_back_right
float32 r_foot_front_left
float32 r_foot_front_right
float32 r_foot_back_left
float32 r_foot_back_right